### ISSUE TITLE
Raspberry Pi B+ Compile-Time Error

### ISSUE THREAD

**Issue by pggsx** [pvachon/tsl-sdr#10]
Currently running an Rpi B+ Model with diet-pi as OS. I ran the concurrencykit and tsl-sdr kit installation and the concurrency-kit compiled and installed successfully. 

However the tsl-sdr installed failed with the archid being not supported. architecture id is armv61. 

What would I need to do to get the tsl-sdr kit to compile with my Rpi?

Also including stack trace for added measure.
SDR is NESDr Smart SDR Antenna Kit

Hope to get this fixed so I can start having some SDR fun!

Error Stack Trace:

Traceback (most recent call last):
  File "/root/tsl-sdr/.waf-1.8.17-52e615d7ea939578c442d3f827a956ed/waflib/Scripting.py", line 110, in waf_entry_point
    run_commands()
  File "/root/tsl-sdr/.waf-1.8.17-52e615d7ea939578c442d3f827a956ed/waflib/Scripting.py", line 167, in run_commands
    parse_options()
  File "/root/tsl-sdr/.waf-1.8.17-52e615d7ea939578c442d3f827a956ed/waflib/Scripting.py", line 140, in parse_options
    Context.create_context('options').execute()
  File "/root/tsl-sdr/.waf-1.8.17-52e615d7ea939578c442d3f827a956ed/waflib/Options.py", line 146, in execute
    super(OptionsContext,self).execute()
  File "/root/tsl-sdr/.waf-1.8.17-52e615d7ea939578c442d3f827a956ed/waflib/Context.py", line 93, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/root/tsl-sdr/.waf-1.8.17-52e615d7ea939578c442d3f827a956ed/waflib/Context.py", line 134, in recurse
    user_function(self)
  File "/root/tsl-sdr/wscript", line 54, in options
    _loadTools(opt)
  File "/root/tsl-sdr/wscript", line 35, in _loadTools
    _checkSupportedArch(cpuArch)
  File "/root/tsl-sdr/wscript", line 30, in _checkSupportedArch
    raise Exception('Unsupported CPU architecture: {}'.format(cpuArchId))
Exception: Unsupported CPU architecture: armv6l

**Comment by pvachon** [comment]
I don't have a Raspberry Pi B+ to test with unfortunately. However, it seems that the B+ has an ARM1176 CPU, which does not support NEON. Unfortunately, that means `multifm' won't work so well. You could hack up the build script to use the unoptimized fallback filtering code (basically similar to armv7l, minus `_USE_ARM_NEON'), but you'll find the performance pretty poor, likely unusable. Note that tools like `decoder' should work fine, though.

We could change this ticket to track adding support for armv6l devices, but even then there will be difficulties achieving required performance with this platform (iirc it only supports VFP), so it might be tough to run `multifm' on it.

If you want to run `multifm', if you can swing it, I recommend grabbing one of the Raspberry Pi 3 boards, or an Orange Pi PC2 or similar. These guys achieve the required performance and work great.

**Comment by pggsx** [comment]
Thanks for the heads up! Would there be any problem running MultiFM via RPi3 VM as an alternative?

**Comment by pggsx** [comment]
I agree emulation would suuper slow but just was curious for alternative options. and Yep I was talking about QEMU specifically for emulation. Interestingly enough there are some projects out there that directly attempt to emulate RPI3s which lead me to question how feasible would it be long-term. Regarding the MultiFM collection infrastructure (which you talked about at Shmoocon), was that mainly just closed-sourced or CUI or are there plans for releasing more information about how collection platforms fit into the whole picture?

**Comment by pvachon** [comment]
Releasing Herbivore as a whole is upcoming soon -- we have a few copyright hurdles that need to be cleared, then we can open up a repo. It's been a matter of other priorities over the last few weeks, unfortunately.

Thanks for attending the talk!

**Comment by pvachon** [comment]
I'm going to close this issue, because we won't be supporting pre-Raspberry Pi 3 devices any time soon.
