### ISSUE TITLE
Build problem in tsl-sdr

### ISSUE THREAD

**Issue by lefko8** [pvachon/tsl-sdr#13]
Building on a Acer C720 Gallium OS Ubuntu variant.  Build fails with this error

Waf: Leaving directory `/root/tsl-sdr/build'
./waf configure && ./waf build failed with the following

 -> task in 'test_ais' failed (exit status 1): 
	{task 140202364006224: cprogram test_ais_demod.c.9.o -> test_ais}
['/usr/bin/gcc', 'ais/test/test_ais_demod.c.9.o', '-o', '/root/tsl-sdr/build/release/test/test_ais', '-Wl,-Bstatic', '-Lrelease/lib', '-lais', '-Wl,-Bdynamic', '-L/usr/local/lib', "-L['/usr/lib/x86_64-linux-gnu']", '-L/usr/local/lib', '-lpthread', '-lrt', '-ljansson', '-ldl', '-lm', '-ltsl', '-ltsltest', '-ltslapp', '-ltslconfig', '-ljansson', '-rdynamic']
 -> task in 'test_pager' failed (exit status 1): 
	{task 140202364005584: cprogram test_mueller_muller.c.7.o,test_pager_flex.c.7.o,test_pager_pocsag.c.7.o -> test_pager}
['/usr/bin/gcc', 'pager/test/test_mueller_muller.c.7.o', 'pager/test/test_pager_flex.c.7.o', 'pager/test/test_pager_pocsag.c.7.o', '-o', '/root/tsl-sdr/build/release/test/test_pager', '-Wl,-Bstatic', '-Lrelease/lib', '-lpager', '-Wl,-Bdynamic', '-L/usr/local/lib', "-L['/usr/lib/x86_64-linux-gnu']", '-L/usr/local/lib', '-lpthread', '-lrt', '-ljansson', '-ldl', '-lm', '-ltsl', '-ltsltest', '-ltslapp', '-ltslconfig', '-ljansson', '-rdynamic']

**Comment by pvachon** [comment]
Hi there - I need the full build log output. Could you please restart building tsl-sdr and capture the full output, from start to finish? Also, please include the output from the configuration log out of waf? (It’s in the build/ directory).

**Comment by virtuallynathan** [comment]
I have the same build failure on Fedora 28 


`[nathan@server tsl-sdr]$ ./waf build clean
Waf: Entering directory `/home/nathan/tools/tsl-sdr/build'
Building version 3d2e3b18f627d544
Pre build...
[28/36] Linking build/release/test/test_pager
[33/36] Linking build/release/test/test_ais
/usr/local/lib/libtsltest.a(main.c.5.o): In function `main':
/home/nathan/tools/tsl/build/../test/main.c:191: multiple definition of `main'
/usr/local/lib/libtsl.a(version_dump.c.7.o):/home/nathan/tools/tsl/build/../tsl/version_dump/version_dump.c:28: first defined here
/usr/local/lib/libtslapp.a(app.c.1.o): In function `app_allocator_init':
/home/nathan/tools/tsl/build/../app/app.c:392: undefined reference to `slab_manager_initialized'
/home/nathan/tools/tsl/build/../app/app.c:435: undefined reference to `allocator_system_init'
/usr/local/lib/libtslapp.a(app.c.1.o): In function `app_bind_cpu_core':
/home/nathan/tools/tsl/build/../app/app.c:305: undefined reference to `cpu_mask_new'
/home/nathan/tools/tsl/build/../app/app.c:309: undefined reference to `cpu_mask_set'
/home/nathan/tools/tsl/build/../app/app.c:313: undefined reference to `cpu_mask_apply'
/home/nathan/tools/tsl/build/../app/app.c:317: undefined reference to `cpu_mask_delete'
/usr/local/lib/libtslapp.a(app.c.1.o): In function `tsl_time_subsys_init':
/home/nathan/tools/tsl/build/../app/app.c:448: undefined reference to `tsl_time_init'
collect2: error: ld returned 1 exit status

/usr/local/lib/libtsltest.a(main.c.5.o): In function `main':
/home/nathan/tools/tsl/build/../test/main.c:191: multiple definition of `main'
/usr/local/lib/libtsl.a(version_dump.c.7.o):/home/nathan/tools/tsl/build/../tsl/version_dump/version_dump.c:28: first defined here
/usr/local/lib/libtslapp.a(app.c.1.o): In function `app_allocator_init':
/home/nathan/tools/tsl/build/../app/app.c:392: undefined reference to `slab_manager_initialized'
/home/nathan/tools/tsl/build/../app/app.c:435: undefined reference to `allocator_system_init'
/usr/local/lib/libtslapp.a(app.c.1.o): In function `app_bind_cpu_core':
/home/nathan/tools/tsl/build/../app/app.c:305: undefined reference to `cpu_mask_new'
/home/nathan/tools/tsl/build/../app/app.c:309: undefined reference to `cpu_mask_set'
/home/nathan/tools/tsl/build/../app/app.c:313: undefined reference to `cpu_mask_apply'
/home/nathan/tools/tsl/build/../app/app.c:317: undefined reference to `cpu_mask_delete'
/usr/local/lib/libtslapp.a(app.c.1.o): In function `tsl_time_subsys_init':
/home/nathan/tools/tsl/build/../app/app.c:448: undefined reference to `tsl_time_init'
collect2: error: ld returned 1 exit status

Waf: Leaving directory `/home/nathan/tools/tsl-sdr/build'
Build failed
 -> task in 'test_ais' failed (exit status 1): 
	{task 139899823820624: cprogram test_ais_demod.c.9.o -> test_ais}
['/usr/bin/gcc', 'ais/test/test_ais_demod.c.9.o', '-o', '/home/nathan/tools/tsl-sdr/build/release/test/test_ais', '-Wl,-Bstatic', '-Lrelease/lib', '-lais', '-Wl,-Bdynamic', '-L/usr/local/lib', "-L['/usr/lib/x86_64-linux-gnu']", '-L/usr/local/lib', '-lpthread', '-lrt', '-ljansson', '-ldl', '-lm', '-ltsl', '-ltsltest', '-ltslapp', '-ltslconfig', '-ljansson', '-rdynamic']
 -> task in 'test_pager' failed (exit status 1): 
	{task 139899823819984: cprogram test_mueller_muller.c.7.o,test_pager_flex.c.7.o,test_pager_pocsag.c.7.o -> test_pager}
['/usr/bin/gcc', 'pager/test/test_mueller_muller.c.7.o', 'pager/test/test_pager_flex.c.7.o', 'pager/test/test_pager_pocsag.c.7.o', '-o', '/home/nathan/tools/tsl-sdr/build/release/test/test_pager', '-Wl,-Bstatic', '-Lrelease/lib', '-lpager', '-Wl,-Bdynamic', '-L/usr/local/lib', "-L['/usr/lib/x86_64-linux-gnu']", '-L/usr/local/lib', '-lpthread', '-lrt', '-ljansson', '-ldl', '-lm', '-ltsl', '-ltsltest', '-ltslapp', '-ltslconfig', '-ljansson', '-rdynamic']`


Configure log: https://gist.github.com/virtuallynathan/17972bb1ff70b987651869af81711fec

**Comment by grostim** [comment]
Similiar problem here:

> pi@RTLSDR:~/tsl-sdr $ ./waf configure
> Setting top to                           : /home/pi/tsl-sdr 
> Setting out to                           : /home/pi/tsl-sdr/build 
> Checking for program 'gcc, cc'           : /usr/bin/gcc 
> Checking for program 'ar'                : /usr/bin/ar 
> Checking for program 'pkg-config'        : /usr/bin/pkg-config 
> Checking for base TSL library            : yes 
> Checking for RTL-SDR library             : yes 
> Checking for ConcurrencyKit              : yes 
> Checking for Jansson (JSON library)      : yes 
> Checking for DespAirspy                  : not found 
> Checking for Ettus UHD                   : not found 
> Building for:                            : armv7l 
> Build environment                        : $$$$$$$$$$$$$$$$$$$$ RELEASE $$$$$$$$$$$$$$$$$$$$ 
> 'configure' finished successfully (6.887s)
> pi@RTLSDR:~/tsl-sdr $ ./waf build
> Waf: Entering directory `/home/pi/tsl-sdr/build'
> Building version 3d2e3b18f627d544
> Pre build...
> [ 1/36] Compiling multifm/costas_demod.c
> [ 2/36] Compiling multifm/demod.c
> [ 3/36] Compiling multifm/fast_atan2f.c
> [ 4/36] Compiling multifm/file_if.c
> [ 5/36] Compiling multifm/fm_demod.c
> [ 6/36] Compiling multifm/multifm.c
> [ 7/36] Compiling multifm/receiver.c
> [ 8/36] Compiling multifm/rtl_sdr_if.c
> [ 9/36] Compiling resampler/resampler.c
> [10/36] Compiling decoder/decoder.c
> [11/36] Compiling filter/direct_fir.c
> [12/36] Compiling filter/polyphase_fir.c
> [13/36] Compiling filter/sample_buf.c
> ../decoder/decoder.c: In function ‘_on_flex_alnum_msg’:
> ../decoder/decoder.c:190:23: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 14 has type ‘uint64_t {aka long long unsigned int}’ [-Wformat=]
>      fprintf(out_file, "{\"proto\":\"flex\",\"type\":\"alphanumeric\",\"timestamp\":\"%04i-%02i-%02i %02i:%02i:%02i UTC\","
>                        ^
> ../decoder/decoder.c: In function ‘_on_flex_num_msg’:
> ../decoder/decoder.c:222:23: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 14 has type ‘uint64_t {aka long long unsigned int}’ [-Wformat=]
>      fprintf(out_file, "{\"proto\":\"flex\",\"type\":\"numeric\",\"timestamp\":\"%04i-%02i-%02i %02i:%02i:%02i UTC\","
>                        ^
> ../decoder/decoder.c: In function ‘_on_flex_siv_msg’:
> ../decoder/decoder.c:254:27: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 14 has type ‘uint64_t {aka long long unsigned int}’ [-Wformat=]
>          fprintf(out_file, "{\"proto\":\"flex\",\"type\":\"tempAddrActivation\",\"timestamp\":\"%04i-%02i-%02i %02i:%02i:%02i UTC\","
>                            ^
> 
> [14/36] Compiling filter/utils.c
> [15/36] Compiling filter/test/test_direct_fir.c
> [16/36] Compiling filter/test/test_polyphase_fir.c
> [17/36] Compiling pager/bch_code.c
> [18/36] Compiling pager/mueller_muller.c
> [19/36] Compiling pager/pager.c
> [20/36] Compiling pager/pager_flex.c
> [21/36] Compiling pager/pager_pocsag.c
> [22/36] Compiling pager/test/test_mueller_muller.c
> [23/36] Compiling pager/test/test_pager_flex.c
> [24/36] Compiling pager/test/test_pager_pocsag.c
> [25/36] Compiling ais/ais_decode.c
> [26/36] Compiling ais/ais_demod.c
> [27/36] Compiling ais/test/test_ais_demod.c
> [28/36] Linking build/release/lib/libfilter.a
> [29/36] Linking build/release/test/test_filter
> [30/36] Linking build/release/bin/multifm
> [31/36] Linking build/release/bin/resampler
> In file included from /home/pi/tsl-sdr/pager/pager.h:10:0,
>                  from ../pager/pager_flex.c:21:
> ../pager/pager_flex.c: In function ‘_pager_flex_decode_tone’:
> /usr/local/include/tsl/tsl/diag.h:107:25: warning: format ‘%zu’ expects argument of type ‘size_t’, but argument 13 has type ‘uint64_t {aka long long unsigned int}’ [-Wformat=]
>          fprintf(stderr, "%04u-%02u-%02u %02u:%02u:%02u [tid=%5d] %%" subsys "-" severity "-" ident ", " message " (%s:%d in %s)\n", _Y, _M, _D, _h, _m, _s, (int)syscall(SYS_gettid), ##__VA_ARGS__, __FILE__, __LINE__, __FUNCTION__); \
>                          ^
> /usr/local/include/tsl/tsl/diag.h:107:25: note: in definition of macro ‘MESSAGE’
>          fprintf(stderr, "%04u-%02u-%02u %02u:%02u:%02u [tid=%5d] %%" subsys "-" severity "-" ident ", " message " (%s:%d in %s)\n", _Y, _M, _D, _h, _m, _s, (int)syscall(SYS_gettid), ##__VA_ARGS__, __FILE__, __LINE__, __FUNCTION__); \
>                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../pager/pager_flex.c:867:9: note: in expansion of macro ‘PAG_MSG’
>          PAG_MSG(SEV_INFO, "TONE", "%02u/%03u/%c [%zu] Sourced Tone: [%08x, %08x]", flex->cycle_id, flex->frame_id, phase + 'A', capcode, first_word, second_word);
>          ^~~~~~~
> /usr/local/include/tsl/tsl/diag.h:107:25: warning: format ‘%zu’ expects argument of type ‘size_t’, but argument 13 has type ‘uint64_t {aka long long unsigned int}’ [-Wformat=]
>          fprintf(stderr, "%04u-%02u-%02u %02u:%02u:%02u [tid=%5d] %%" subsys "-" severity "-" ident ", " message " (%s:%d in %s)\n", _Y, _M, _D, _h, _m, _s, (int)syscall(SYS_gettid), ##__VA_ARGS__, __FILE__, __LINE__, __FUNCTION__); \
>                          ^
> /usr/local/include/tsl/tsl/diag.h:107:25: note: in definition of macro ‘MESSAGE’
>          fprintf(stderr, "%04u-%02u-%02u %02u:%02u:%02u [tid=%5d] %%" subsys "-" severity "-" ident ", " message " (%s:%d in %s)\n", _Y, _M, _D, _h, _m, _s, (int)syscall(SYS_gettid), ##__VA_ARGS__, __FILE__, __LINE__, __FUNCTION__); \
>                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../pager/pager_flex.c:870:9: note: in expansion of macro ‘PAG_MSG’
>          PAG_MSG(SEV_INFO, "TONE", "%02u/%03u/%c [%zu] Sequenced Tone: [%08x, %08x]", flex->cycle_id, flex->frame_id, phase + 'A', capcode, first_word, second_word);
>          ^~~~~~~
> ../pager/pager_flex.c: In function ‘_pager_flex_decode_short_instruction_vec’:
> /usr/local/include/tsl/tsl/diag.h:107:25: warning: format ‘%zu’ expects argument of type ‘size_t’, but argument 13 has type ‘uint64_t {aka long long unsigned int}’ [-Wformat=]
>          fprintf(stderr, "%04u-%02u-%02u %02u:%02u:%02u [tid=%5d] %%" subsys "-" severity "-" ident ", " message " (%s:%d in %s)\n", _Y, _M, _D, _h, _m, _s, (int)syscall(SYS_gettid), ##__VA_ARGS__, __FILE__, __LINE__, __FUNCTION__); \
>                          ^
> /usr/local/include/tsl/tsl/diag.h:107:25: note: in definition of macro ‘MESSAGE’
>          fprintf(stderr, "%04u-%02u-%02u %02u:%02u:%02u [tid=%5d] %%" subsys "-" severity "-" ident ", " message " (%s:%d in %s)\n", _Y, _M, _D, _h, _m, _s, (int)syscall(SYS_gettid), ##__VA_ARGS__, __FILE__, __LINE__, __FUNCTION__); \
>                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../pager/pager_flex.c:914:9: note: in expansion of macro ‘PAG_MSG’
>          PAG_MSG(SEV_INFO, "SIV", "%02u/%03u/%c - [%9zu] System Event (data = %08x)", flex->cycle_id, flex->frame_id, phase + 'A', capcode, siv_data);
>          ^~~~~~~
> /usr/local/include/tsl/tsl/diag.h:107:25: warning: format ‘%zu’ expects argument of type ‘size_t’, but argument 13 has type ‘uint64_t {aka long long unsigned int}’ [-Wformat=]
>          fprintf(stderr, "%04u-%02u-%02u %02u:%02u:%02u [tid=%5d] %%" subsys "-" severity "-" ident ", " message " (%s:%d in %s)\n", _Y, _M, _D, _h, _m, _s, (int)syscall(SYS_gettid), ##__VA_ARGS__, __FILE__, __LINE__, __FUNCTION__); \
>                          ^
> /usr/local/include/tsl/tsl/diag.h:107:25: note: in definition of macro ‘MESSAGE’
>          fprintf(stderr, "%04u-%02u-%02u %02u:%02u:%02u [tid=%5d] %%" subsys "-" severity "-" ident ", " message " (%s:%d in %s)\n", _Y, _M, _D, _h, _m, _s, (int)syscall(SYS_gettid), ##__VA_ARGS__, __FILE__, __LINE__, __FUNCTION__); \
>                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../pager/pager_flex.c:917:9: note: in expansion of macro ‘PAG_MSG’
>          PAG_MSG(SEV_INFO, "SIV", "%02u/%03u/%c - [%9zu] Reserved Test (data = %08x)", flex->cycle_id, flex->frame_id, phase + 'A', capcode, siv_data);
>          ^~~~~~~
> /usr/local/include/tsl/tsl/diag.h:107:25: warning: format ‘%zu’ expects argument of type ‘size_t’, but argument 13 has type ‘uint64_t {aka long long unsigned int}’ [-Wformat=]
>          fprintf(stderr, "%04u-%02u-%02u %02u:%02u:%02u [tid=%5d] %%" subsys "-" severity "-" ident ", " message " (%s:%d in %s)\n", _Y, _M, _D, _h, _m, _s, (int)syscall(SYS_gettid), ##__VA_ARGS__, __FILE__, __LINE__, __FUNCTION__); \
>                          ^
> /usr/local/include/tsl/tsl/diag.h:107:25: note: in definition of macro ‘MESSAGE’
>          fprintf(stderr, "%04u-%02u-%02u %02u:%02u:%02u [tid=%5d] %%" subsys "-" severity "-" ident ", " message " (%s:%d in %s)\n", _Y, _M, _D, _h, _m, _s, (int)syscall(SYS_gettid), ##__VA_ARGS__, __FILE__, __LINE__, __FUNCTION__); \
>                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../pager/pager_flex.c:920:9: note: in expansion of macro ‘PAG_MSG’
>          PAG_MSG(SEV_INFO, "SIV", "%02u/%03u/%c - [%9zu] Unknown SIV %u (data = %08x)", flex->cycle_id, flex->frame_id, phase + 'A', capcode,
>          ^~~~~~~
> ../pager/pager_flex.c: In function ‘_pager_flex_decode_vector’:
> /usr/local/include/tsl/tsl/diag.h:107:25: warning: format ‘%zu’ expects argument of type ‘size_t’, but argument 13 has type ‘uint64_t {aka long long unsigned int}’ [-Wformat=]
>          fprintf(stderr, "%04u-%02u-%02u %02u:%02u:%02u [tid=%5d] %%" subsys "-" severity "-" ident ", " message " (%s:%d in %s)\n", _Y, _M, _D, _h, _m, _s, (int)syscall(SYS_gettid), ##__VA_ARGS__, __FILE__, __LINE__, __FUNCTION__); \
>                          ^
> /usr/local/include/tsl/tsl/diag.h:107:25: note: in definition of macro ‘MESSAGE’
>          fprintf(stderr, "%04u-%02u-%02u %02u:%02u:%02u [tid=%5d] %%" subsys "-" severity "-" ident ", " message " (%s:%d in %s)\n", _Y, _M, _D, _h, _m, _s, (int)syscall(SYS_gettid), ##__VA_ARGS__, __FILE__, __LINE__, __FUNCTION__); \
>                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../pager/pager_flex.c:1022:9: note: in expansion of macro ‘PAG_MSG’
>          PAG_MSG(SEV_INFO, "UNSUPP-MSG", "%02u/%03u/%c [%9zu] Unsupported Message: %s", flex->cycle_id, flex->frame_id, phase + 'A', capcode,  __pager_flex_type_code[vec_type]);
>          ^~~~~~~
> ../pager/pager_flex.c: In function ‘_pager_flex_phase_process’:
> /usr/local/include/tsl/tsl/diag.h:107:25: warning: format ‘%zu’ expects argument of type ‘size_t’, but argument 13 has type ‘uint64_t {aka long long unsigned int}’ [-Wformat=]
>          fprintf(stderr, "%04u-%02u-%02u %02u:%02u:%02u [tid=%5d] %%" subsys "-" severity "-" ident ", " message " (%s:%d in %s)\n", _Y, _M, _D, _h, _m, _s, (int)syscall(SYS_gettid), ##__VA_ARGS__, __FILE__, __LINE__, __FUNCTION__); \
>                          ^
> /usr/local/include/tsl/tsl/diag.h:107:25: note: in definition of macro ‘MESSAGE’
>          fprintf(stderr, "%04u-%02u-%02u %02u:%02u:%02u [tid=%5d] %%" subsys "-" severity "-" ident ", " message " (%s:%d in %s)\n", _Y, _M, _D, _h, _m, _s, (int)syscall(SYS_gettid), ##__VA_ARGS__, __FILE__, __LINE__, __FUNCTION__); \
>                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../pager/pager_flex.c:1187:13: note: in expansion of macro ‘PAG_MSG’
>              PAG_MSG(SEV_WARNING, "BCH-ERROR", "%02u/%03u/%c [%zu] Uncorrectable Error",
>              ^~~~~~~
> 
> [32/36] Linking build/release/lib/libais.a
> [33/36] Linking build/release/lib/libpager.a
> [34/36] Linking build/release/bin/decoder
> [35/36] Linking build/release/test/test_pager
> /usr/local/lib/libtslapp.a(app.c.1.o) : Dans la fonction « app_allocator_init » :
> /home/pi/tsl/build/../app/app.c:392 : référence indéfinie vers « slab_manager_initialized »
> /home/pi/tsl/build/../app/app.c:392 : référence indéfinie vers « slab_manager_initialized »
> /home/pi/tsl/build/../app/app.c:435 : référence indéfinie vers « allocator_system_init »
> /usr/local/lib/libtslconfig.a(engine.c.3.o) : Dans la fonction « config_add_system_config » :
> /home/pi/tsl/build/../config/engine.c:218 : référence indéfinie vers « tasprintf »
> /usr/local/lib/libtslconfig.a(engine.c.3.o) : Dans la fonction « config_get » :
> /home/pi/tsl/build/../config/engine.c:304 : référence indéfinie vers « tstrdup »
> collect2: error: ld returned 1 exit status
> 
> /usr/local/lib/libtslapp.a(app.c.1.o) : Dans la fonction « app_allocator_init » :
> /home/pi/tsl/build/../app/app.c:392 : référence indéfinie vers « slab_manager_initialized »
> /home/pi/tsl/build/../app/app.c:392 : référence indéfinie vers « slab_manager_initialized »
> /home/pi/tsl/build/../app/app.c:435 : référence indéfinie vers « allocator_system_init »
> /usr/local/lib/libtslapp.a(app.c.1.o) : Dans la fonction « tsl_time_subsys_init » :
> /home/pi/tsl/build/../app/app.c:448 : référence indéfinie vers « tsl_time_init »
> /usr/local/lib/libtslapp.a(app.c.1.o) : Dans la fonction « app_bind_cpu_core » :
> /home/pi/tsl/build/../app/app.c:305 : référence indéfinie vers « cpu_mask_new »
> /home/pi/tsl/build/../app/app.c:309 : référence indéfinie vers « cpu_mask_set »
> /home/pi/tsl/build/../app/app.c:313 : référence indéfinie vers « cpu_mask_apply »
> /home/pi/tsl/build/../app/app.c:317 : référence indéfinie vers « cpu_mask_delete »
> /usr/local/lib/libtslconfig.a(engine.c.3.o) : Dans la fonction « config_add_system_config » :
> /home/pi/tsl/build/../config/engine.c:218 : référence indéfinie vers « tasprintf »
> /usr/local/lib/libtslconfig.a(engine.c.3.o) : Dans la fonction « config_get » :
> /home/pi/tsl/build/../config/engine.c:304 : référence indéfinie vers « tstrdup »
> collect2: error: ld returned 1 exit status
> 
> /usr/local/lib/libtslapp.a(app.c.1.o) : Dans la fonction « app_allocator_init » :
> /home/pi/tsl/build/../app/app.c:392 : référence indéfinie vers « slab_manager_initialized »
> /home/pi/tsl/build/../app/app.c:392 : référence indéfinie vers « slab_manager_initialized »
> /home/pi/tsl/build/../app/app.c:435 : référence indéfinie vers « allocator_system_init »
> /usr/local/lib/libtslapp.a(app.c.1.o) : Dans la fonction « tsl_time_subsys_init » :
> /home/pi/tsl/build/../app/app.c:448 : référence indéfinie vers « tsl_time_init »
> /usr/local/lib/libtslapp.a(app.c.1.o) : Dans la fonction « app_bind_cpu_core » :
> /home/pi/tsl/build/../app/app.c:305 : référence indéfinie vers « cpu_mask_new »
> /home/pi/tsl/build/../app/app.c:309 : référence indéfinie vers « cpu_mask_set »
> /home/pi/tsl/build/../app/app.c:313 : référence indéfinie vers « cpu_mask_apply »
> /home/pi/tsl/build/../app/app.c:317 : référence indéfinie vers « cpu_mask_delete »
> /usr/local/lib/libtslconfig.a(engine.c.3.o) : Dans la fonction « config_add_system_config » :
> /home/pi/tsl/build/../config/engine.c:218 : référence indéfinie vers « tasprintf »
> /usr/local/lib/libtslconfig.a(engine.c.3.o) : Dans la fonction « config_get » :
> /home/pi/tsl/build/../config/engine.c:304 : référence indéfinie vers « tstrdup »
> collect2: error: ld returned 1 exit status
> 
> /usr/local/lib/libtsltest.a(main.c.5.o) : Dans la fonction « main » :
> /home/pi/tsl/build/../test/main.c:191 : définitions multiples de « main »
> /usr/local/lib/libtsl.a(version_dump.c.7.o):/home/pi/tsl/build/../tsl/version_dump/version_dump.c:28 : défini pour la première fois ici
> /usr/local/lib/libtslapp.a(app.c.1.o) : Dans la fonction « app_allocator_init » :
> /home/pi/tsl/build/../app/app.c:392 : référence indéfinie vers « slab_manager_initialized »
> /home/pi/tsl/build/../app/app.c:392 : référence indéfinie vers « slab_manager_initialized »
> /home/pi/tsl/build/../app/app.c:435 : référence indéfinie vers « allocator_system_init »
> /usr/local/lib/libtslapp.a(app.c.1.o) : Dans la fonction « tsl_time_subsys_init » :
> /home/pi/tsl/build/../app/app.c:448 : référence indéfinie vers « tsl_time_init »
> /usr/local/lib/libtslapp.a(app.c.1.o) : Dans la fonction « app_bind_cpu_core » :
> /home/pi/tsl/build/../app/app.c:305 : référence indéfinie vers « cpu_mask_new »
> /home/pi/tsl/build/../app/app.c:309 : référence indéfinie vers « cpu_mask_set »
> /home/pi/tsl/build/../app/app.c:313 : référence indéfinie vers « cpu_mask_apply »
> /home/pi/tsl/build/../app/app.c:317 : référence indéfinie vers « cpu_mask_delete »
> collect2: error: ld returned 1 exit status
> 
> Waf: Leaving directory `/home/pi/tsl-sdr/build'
> Build failed
>  -> task in 'multifm' failed (exit status 1): 
> 	{task 1985349776: cprogram costas_demod.c.1.o,demod.c.1.o,fast_atan2f.c.1.o,file_if.c.1.o,fm_demod.c.1.o,multifm.c.1.o,receiver.c.1.o,rtl_sdr_if.c.1.o -> multifm}
> ['/usr/bin/gcc', 'multifm/costas_demod.c.1.o', 'multifm/demod.c.1.o', 'multifm/fast_atan2f.c.1.o', 'multifm/file_if.c.1.o', 'multifm/fm_demod.c.1.o', 'multifm/multifm.c.1.o', 'multifm/receiver.c.1.o', 'multifm/rtl_sdr_if.c.1.o', '-o', '/home/pi/tsl-sdr/build/release/bin/multifm', '-Wl,-Bstatic', '-Lrelease/lib', '-lfilter', '-Wl,-Bdynamic', '-L/usr/local/lib', '-L/usr/local/lib', '-lpthread', '-lrt', '-ljansson', '-ldl', '-lm', '-ltsl', '-ltsltest', '-ltslapp', '-ltslconfig', '-ljansson', '-lrtlsdr', '-rdynamic']
>  -> task in 'resampler' failed (exit status 1): 
> 	{task 1985432464: cprogram resampler.c.2.o -> resampler}
> ['/usr/bin/gcc', 'resampler/resampler.c.2.o', '-o', '/home/pi/tsl-sdr/build/release/bin/resampler', '-Wl,-Bstatic', '-Lrelease/lib', '-lfilter', '-Wl,-Bdynamic', '-L/usr/local/lib', '-L/usr/local/lib', '-lpthread', '-lrt', '-ljansson', '-ldl', '-lm', '-ltsl', '-ltsltest', '-ltslapp', '-ltslconfig', '-ljansson', '-rdynamic']
>  -> task in 'decoder' failed (exit status 1): 
> 	{task 1985432720: cprogram decoder.c.3.o -> decoder}
> ['/usr/bin/gcc', 'decoder/decoder.c.3.o', '-o', '/home/pi/tsl-sdr/build/release/bin/decoder', '-Wl,-Bstatic', '-Lrelease/lib', '-lfilter', '-lpager', '-lais', '-Wl,-Bdynamic', '-L/usr/local/lib', '-L/usr/local/lib', '-lpthread', '-lrt', '-ljansson', '-ldl', '-lm', '-ltsl', '-ltsltest', '-ltslapp', '-ltslconfig', '-ljansson', '-rdynamic']
>  -> task in 'test_pager' failed (exit status 1): 
> 	{task 1985479248: cprogram test_mueller_muller.c.7.o,test_pager_flex.c.7.o,test_pager_pocsag.c.7.o -> test_pager}
> ['/usr/bin/gcc', 'pager/test/test_mueller_muller.c.7.o', 'pager/test/test_pager_flex.c.7.o', 'pager/test/test_pager_pocsag.c.7.o', '-o', '/home/pi/tsl-sdr/build/release/test/test_pager', '-Wl,-Bstatic', '-Lrelease/lib', '-lpager', '-Wl,-Bdynamic', '-L/usr/local/lib', '-L/usr/local/lib', '-lpthread', '-lrt', '-ljansson', '-ldl', '-lm', '-ltsl', '-ltsltest', '-ltslapp', '-ltslconfig', '-ljansson', '-rdynamic']

**Comment by pvachon** [comment]
Just was able to reproduce the issue, I think I'll have a fix shortly.

**Comment by pvachon** [comment]
Closing this issue -- have had reports that this fixed the problem for other users. Please open a new issue if you run into further problems!
