### ISSUE TITLE
SSE4a support

### ISSUE THREAD

**Issue by lilrags16** [pvachon/tsl-sdr#17]
`rttest@rttest:~$ multifm /etc/radiotape/rt_home_test.json /etc/radiotape/filter.                                                                                                                                                             json
2020-07-14 07:01:36 [tid= 1176] %CPUFEATURE-F-MISSING-CPUID-FEATURE, This applic                                                                                                                                                             ation requires SSE 4.2 be present and enabled. (/home/rttest/tsl/app/cpufeatures                                                                                                                                                             .c:128 in app_cpufeatures_check_at_init)
The application has PANICked. Reason:
Failed CPU feature checks, aborting. If this is on a 12Sided appliance, please c                                                                                                                                                             ontact 12Sided support at support@12sidedtech.com.

Application [version=63178348d85f9afc] terminating at /home/rttest/tsl/app/cpufe                                                                                                                                                             atures.c:152 [thread=1176]
Call backtrace:
multifm(panic+0x9c)[0x564857d99388]
multifm(app_cpufeatures_check_at_init+0x3ef)[0x564857d96379]
multifm(app_init+0x73)[0x564857d95ad8]
multifm(main+0x26e)[0x564857d8bf0e]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f982ab870b3]
multifm(_start+0x2e)[0x564857d8c44e]
Aborted (core dumped)`

`rttest@rttest:~$ lscpu

Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          1
On-line CPU(s) list:             0
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      16
Model:                           5
Model name:                      AMD Athlon(tm) II X3 445 Processor
Stepping:                        3
CPU MHz:                         3113.984
BogoMIPS:                        6227.96
Virtualization:                  AMD-V
Hypervisor vendor:               VMware
Virtualization type:             full
L1d cache:                       64 KiB
L1i cache:                       64 KiB
L2 cache:                        512 KiB
NUMA node0 CPU(s):               0
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Not affected
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user
                                  pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full AMD retpoline, STIBP disabled,
                                  RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtr
                                 r pge mca cmov pat pse36 clflush mmx fxsr sse s
                                 se2 syscall nx mmxext fxsr_opt pdpe1gb rdtscp l
                                 m 3dnowext 3dnow constant_tsc rep_good nopl tsc
                                 _reliable nonstop_tsc cpuid pni cx16 popcnt hyp
                                 ervisor lahf_lm svm extapic cr8_legacy abm sse4
                                 a misalignsse 3dnowprefetch osvw vmmcall npt sv
                                 m_lock nrip_save overflow_recov succor
rttest@rttest:~$ lscpu | grep sse
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl tsc_reliable nonstop_tsc cpuid pni cx16 popcnt hypervisor lahf_lm svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw vmmcall npt svm_lock nrip_save overflow_recov succor`

**Comment by pvachon** [comment]
A bit of an older CPU, but the good news is that I don't believe there's any explicit requirement for SSE 4.2 in `tsl-sdr`. I have put a fix in place in https://github.com/pvachon/tsl/commit/c4f7e827203191d2547de07f2798443993dade2f, could you test to make sure it works? I don't have any x86 hardware without SSE 4.2 around to explicitly test with.

**Comment by lilrags16** [comment]
@pvachon I will give it a shot

**Comment by pvachon** [comment]
Any updates? LMK if I can close the issue. Thanks!

**Comment by pvachon** [comment]
Hopefully this is fixed! Closing the issue, but please reopen if the problem persists.

**Comment by lilrags16** [comment]
Issue had been fixed! Thank you!
