### ISSUE TITLE
Package despairspy not found

### ISSUE THREAD

**Issue by Joopjr** [pvachon/tsl-sdr#18]
I want to install TSL-SDR to use it with my Airspy Mini. Although I've installed [libdespairspy](https://github.com/pvachon/despairspy) it isn't recognized while running cmake on TSL-SDR.

```
USER@HOSTNAME:/(***)/tsl-sdr-master/build# cmake -DCMAKE_BUILD_TYPE=Release ..
-- CPU Archiecture is armv7l
-- Enabling NEON, setting CPU Architecture to armv7-a
-- Checking for module 'librtlsdr'
--   No package 'librtlsdr' found
-- Checking for module 'despairspy'
--   No package 'despairspy' found
-- Checking for module 'uhd'
--   No package 'uhd' found
-- Configuring done
-- Generating done
-- Build files have been written to: /(***)/tsl-sdr-master/build
```

All the airspy commands can be run (after installing libdespairspy). This suggest that the install was completely flawless so I'm unsure why it isn't recognized.
```
USER@HOSTNAME:/(***)# airspy_info
airspy_lib_version: 1.0.9

Found AirSpy board 1
Board ID Number: 0 (AIRSPY)
Firmware Version: AirSpy MINI v1.0.0-rc10-0-g946184a 2016-09-19
Part ID Number: 0x6906002B 0x00000030
Serial Number: (***)
Supported sample rates:
        6.000000 MSPS
        3.000000 MSPS
Close board 1

```

When I search for "Airspy" it seems like the library is installed:
```
USER@HOSTNAME:/(***)# find / -name "*airspy*"
/usr/local/include/libdespairspy
/usr/local/include/libdespairspy/airspy.h
/usr/local/include/libdespairspy/airspy_commands.h
/usr/local/include/libairspy
/usr/local/include/libairspy/airspy.h
/usr/local/include/libairspy/airspy_commands.h
/usr/local/bin/airspy_rx
/usr/local/bin/airspy_spiflash
/usr/local/bin/airspy_r820t
/usr/local/bin/airspy_gpiodir
/usr/local/bin/airspy_gpio
/usr/local/bin/airspy_si5351c
/usr/local/bin/airspy_lib_version
/usr/local/bin/airspy_info
/usr/local/lib/libdespairspy.so
/usr/local/lib/pkgconfig/libdespairspy.pc
/usr/local/lib/pkgconfig/libairspy.pc
/usr/local/lib/libdespairspy.so.1.0.9
/usr/local/lib/libairspy.so.1.0.9
/usr/local/lib/libairspy.so.0
/usr/local/lib/libairspy.so
/usr/local/lib/libairspy.a
/usr/local/lib/libdespairspy.so.0
/etc/udev/rules.d/52-airspy.rules

```

----------------------

I've found the issue. First of all the readme at [libdespairspy](https://github.com/pvachon/despairspy) is only for the [airspyone_host](https://github.com/airspy/airspyone_host) and **NOT** for despairspy. To compile these you've to download the libdespairspy manually and can pretty much follow the same steps but you'll have to be in the "libdespairspy" folder.

After this I still had issues because CMAKE for TSL-SDR still didn't see the "despairspy". I have fixed this by changing line 71 in "CMakeLists.txt" to:
`pkg_check_modules(DESPAIRSPY libdespairspy)`

**Comment by pvachon** [comment]
Hey! Appreciate the bug report -- it took me a bit of time to get a chance to poke at this one. A few things got broken when I moved the project from `waf` to CMake, and this was one of them.

I've just pushed a few fixes that fix this, and generally improve things (also fixed the despairspy repo). Hopefully other folks won't run into the issues you have.
