### ISSUE TITLE
multi-fm and decoder  or multimon-ng and multi-fm 

### ISSUE THREAD

**Issue by bertonumber1** [pvachon/tsl-sdr#25]
First of all thank you for your work on the project 
Not so much an issue but a cry for help. 
Please delete if inappropriate and accept my apologies. 

I am currently using a Raspberry pi, Rtl-sdr and multimon-ng and rtlfmto decode a pager frequency. It works. 

However, I would like to be able to decode further two frequencies simultaneously.
The problem apart from my Linux skills being basic is I am unsure how to send multiple frequencies to be decoded.

Am I better scrapping multimon-ng/rtl-fm and using multi-fm and decoder to achieve this?

The frequencies I am interested in are all 153mhz allocated but one is on 147.800 mhz which is outwith the RTL bandwidth.

Any assistance / advice would be a real help and greatly appreciated.

Thank you

**Comment by pvachon** [comment]
Hi there. I think your best bet is two RTL-SDRs: 1 for the 147.8MHz band, and one for the channels around 153MHz.

MultiFM will help you extract the channels around 153MHz (see the sample config at https://github.com/pvachon/tsl-sdr/blob/master/etc/multifm.json for FLEX... there is a similar config for POCSAG in that directory), which it will then pipe into two FIFOs, which must be created with `mkfifo` before launching `multifm`. Then you can follow the instructions at https://github.com/pvachon/tsl-sdr/wiki/Using-Decoder to use the POCSAG/FLEX decoders.

Let me know if you have any troubles following the documentation, it might be a bit sparse.

**Comment by bertonumber1** [comment]
Hi @pvachon
Thanks for your response and providing the links to these configs.
I will have a look and play around with them when home from work.
I was thinking along the same lines as the 147.8 frequency outwith the 153.0mhz  bandwidth.

I am having good results with a nooleec sdr and a piece of rigid wire inside the inner core of the SMA connection. Due to the high power the pocsag transmissions I guess. 

I have another rtl dongle so I will get to changing the serial and hook it up.

I'll report back with results.

Thanks again

Rab
