### ISSUE TITLE
Debian/Raspbian/Ubuntu Packaging

### ISSUE THREAD

**Issue by pvachon** [pvachon/tsl-sdr#7]
Close this issue when there is a means to package for Debian, Raspbian and Ubuntu natively. This should include support for packaging on ARMv7, AArch64 and x86_64 at a minimum.

**Comment by liuqun** [comment]
Packaging support: https://github.com/liuqun/tsl/tree/deb

**Comment by pvachon** [comment]
Packaging is now supported through `cpack`.
